services:
  spring-boot-app:
    build:
      context: server
    ports:
      - "8080:8080"

  react-app:
    build:
      context: client
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app
